title:            Aravind Selvan
description:      A responsive Jekyll theme large featured images and solid typography.
#Comment out url when working locally to resolve base urls correctly
url:              http://aravindselvan.com
#url:              http://localhost:4000

disqus_shortname: aravindselvan

# Owner/author information
owner:
  name:           Aravind Selvan
  avatar:         bio-photo.jpg
  bio:            "Programmer, Learner, Bettering myself each day on what I do."
  email:          araivnd646@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter: aravind646        
  facebook: aravind646      
  github: aravind646        
  stackoverflow: 
  linkedin:       
  instagram:      
  lastfm:         
  tumblr: 
  pinterest: 
  foursquare: 
  steam: 
  dribbble: 

  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Blog
    url: /blog/
  # - title: Made Mistakes
  #   url: http://mademistakes.com
  #   external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Asia/Kolkata
#America/New_York
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]